### ISSUE TITLE
Omvandla till guard statement?

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-theo-wiik/webbserverprojekt#11]
Eller flytta till before-filter?

Exempel på guard statement
````
    get '/cart' do
        redirect /login unless session[:id]
        ...
    end
````
https://github.com/itggot-theo-wiik/webbserverprojekt/blob/735074f402cebc092b76afb48f4207af47f68b6d/main.rb#L160-L176

**Comment by itggot-theo-wiik** [comment]
#7df1e01

**Comment by itggot-theo-wiik** [comment]
Kolla referensen ovan
