### ISSUE TITLE
Uppdatera admin routes

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-theo-wiik/webbserverprojekt#13]
De verkar gamla?

**Comment by itggot-theo-wiik** [comment]
`slim :'admin/admin'`

Jag förmodar att det är detta som du reagerar på. Det är för att jag har lagt alla mina admin slim filer i en egen mapp

**Comment by itggot-daniel-berg** [comment]
Jag tror det var det här jag såg, att du anropade databasen i main

https://github.com/itggot-theo-wiik/webbserverprojekt/blob/028d48d43668aaedefd28591875ea8b883d1c485/main.rb#L341

Flytta slumpgenereringen en metod i lämplig modellklass
