### ISSUE TITLE
Array#map

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-theo-wiik/webbserverprojekt#15]
Put on your big boy pants and convert to Array#map.

https://github.com/itggot-theo-wiik/webbserverprojekt/blob/735074f402cebc092b76afb48f4207af47f68b6d/models/baseclass.rb#L32-L35

**Comment by itggot-daniel-berg** [comment]
https://github.com/itggot-theo-wiik/webbserverprojekt/blob/735074f402cebc092b76afb48f4207af47f68b6d/models/size.rb#L13-L17

**Comment by itggot-theo-wiik** [comment]
done
