### ISSUE TITLE
Vad är detta för fil?

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-theo-wiik/webbserverprojekt#4]
https://github.com/itggot-theo-wiik/webbserverprojekt/blob/735074f402cebc092b76afb48f4207af47f68b6d/misc/item.rb#L1-L55

**Comment by itggot-theo-wiik** [comment]
En gammal fil som jag inte använder, men jag skulle kanske behöva kolla vad jag hade döpt variablerna så jag gjorde en kopia innan jag ändrade på den
